In [1]:
import numpy as np

In [3]:
nd1 = np.zeros(shape = (10,10),dtype=np.int8)
nd1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [4]:
nd1[[0,-1]]=1

In [5]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [6]:
nd1[:,[0,-1]]=1
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [7]:
np.array([0,1,2,3,4]*5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
nd2 = np.random.randint(1,10,size=10)
nd2

array([6, 9, 3, 4, 3, 8, 8, 4, 4, 6])

In [10]:
v_max =nd2.max()
cond = nd2 == v_max
nd2[cond]

array([9])

In [11]:
nd2 == v_max

array([False,  True, False, False, False, False, False, False, False,
       False])

In [14]:
v_min = nd2.min()
index = np.argwhere(nd2 == v_min)
index
for i in index:
    nd2[i[0]] = 1024
nd2

array([   6,    9, 1024,    4, 1024,    8,    8,    4,    4,    6])

In [16]:
nd3 = np.random.randint(0,150,size=(5,5))
nd3

array([[ 97,  85,  49, 104,  84],
       [102,  47,  99, 123,  67],
       [133, 131,  87,  41,   2],
       [ 61, 141,  49, 134, 110],
       [ 70,  42, 137,  48, 134]])

In [17]:
index = [1,3,2,0,4]

nd3[index]

array([[102,  47,  99, 123,  67],
       [ 61, 141,  49, 134, 110],
       [133, 131,  87,  41,   2],
       [ 97,  85,  49, 104,  84],
       [ 70,  42, 137,  48, 134]])

In [21]:
#数据多的时候代码解决
index = nd3[:,2].argsort()
nd3[index]

array([[ 97,  85,  49, 104,  84],
       [ 61, 141,  49, 134, 110],
       [133, 131,  87,  41,   2],
       [102,  47,  99, 123,  67],
       [ 70,  42, 137,  48, 134]])

In [22]:
nd4=np.random.randint(0,10,size=(3,4,5,6))
nd4


array([[[[8, 3, 2, 8, 3, 5],
         [1, 0, 1, 3, 6, 7],
         [9, 7, 5, 3, 4, 6],
         [4, 1, 3, 2, 4, 6],
         [6, 1, 8, 7, 3, 5]],

        [[9, 4, 5, 8, 8, 0],
         [1, 8, 1, 4, 7, 4],
         [3, 7, 3, 0, 4, 1],
         [2, 9, 2, 8, 4, 3],
         [7, 9, 5, 0, 0, 6]],

        [[6, 9, 5, 6, 8, 6],
         [9, 9, 3, 3, 8, 0],
         [2, 1, 1, 2, 4, 1],
         [9, 2, 8, 2, 6, 3],
         [9, 5, 6, 0, 1, 3]],

        [[1, 9, 3, 1, 1, 1],
         [9, 9, 4, 5, 6, 6],
         [8, 7, 0, 5, 8, 9],
         [2, 6, 6, 9, 9, 4],
         [7, 9, 1, 8, 0, 6]]],


       [[[4, 0, 3, 6, 6, 6],
         [4, 0, 9, 0, 3, 4],
         [8, 5, 3, 3, 7, 6],
         [3, 1, 4, 7, 8, 3],
         [2, 4, 8, 7, 0, 6]],

        [[8, 6, 6, 8, 9, 6],
         [3, 9, 6, 8, 1, 9],
         [0, 3, 1, 6, 9, 9],
         [1, 3, 7, 0, 3, 5],
         [6, 4, 1, 7, 6, 9]],

        [[0, 9, 8, 4, 1, 3],
         [2, 5, 0, 1, 0, 2],
         [7, 9, 3, 2, 2, 0],
         [3, 4, 5, 9, 5, 6],


In [23]:
nd4.sum(axis = -1).sum(axis=-1).shape

(3, 4)

In [24]:
nd4.sum(axis= (-1,2))

array([[131, 132, 137, 159],
       [130, 159, 124, 122],
       [138, 140, 143, 132]])

In [28]:
nd1 = np.arange(1,6)
nd1
nd2 = np.zeros(17,dtype=np.int8)
print(nd1,nd2)
nd2[::4]=nd1
nd2

[1 2 3 4 5] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5], dtype=int8)

In [30]:
# 14.创建一个10万长度的随机数组,使用两种方法对其中求三次方,比较事件
nd5 = np.random.rand(10000)
nd5

array([0.62927552, 0.07150784, 0.4201734 , ..., 0.04565221, 0.53670613,
       0.17454046])

In [31]:
%%time
np.power(nd5,3) #高效

Wall time: 998 µs


array([2.49185359e-01, 3.65646146e-04, 7.41798004e-02, ...,
       9.51448596e-05, 1.54600062e-01, 5.31726511e-03])

In [32]:
%%time
ret=[]
for i in nd5:
    ret.append(i**3)

Wall time: 4.99 ms


In [34]:
#	15.创建一个5*3随机矩阵和一个3*2的随机矩阵,求矩阵*   矩阵运算要对齐
a=np.random.randint(0,10,size=(5,3))
b=np.random.randint(0,10,(3,2))
np.dot(a,b)

array([[ 26,  21],
       [ 10,  10],
       [ 99, 114],
       [115, 110],
       [ 97,  72]])