In [1]:
1+1

2

In [2]:
a=1024
b=2024

In [3]:
a

1024

In [4]:
b

2024

In [21]:
print(a)
print(b)
print("aaa")

1024
2024
aaa


In [24]:
a+b

3048

In [27]:
def add(x,y):
    return x+y

In [28]:
add(a,b)

3048

In [29]:
import requests as requests

In [30]:
import numpy as np

In [35]:
np.random.randint(0,100,1)

array([44])

In [39]:
import time

In [40]:
time.time()

1615196120.679903

In [41]:
def sum2(x):
    ret=0
    for i in x:
        ret+=i
    return ret

In [50]:
x=np.arange(0,10000,1)
x


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [51]:
# 计时
%time sum2(x)

Wall time: 996 µs


49995000

In [53]:
y=np.arange(0,5000,1)
y

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [54]:
# 计时
%time sum2(x)
#多行代码,计算他的运行时间
sum2(y)

Wall time: 1.01 ms


12497500

In [55]:
%%timeit
sum2(x)
sum2(y)

1.33 ms ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [57]:
%ls

 驱动器 E 中的卷是 项目编程资料coding
 卷的序列号是 1E84-11FA

 E:\jupyter_py\01-python数据分析\HZh1807\jupyter-HelloWorld 的目录

2021/03/08  18:22    <DIR>          .
2021/03/08  18:22    <DIR>          ..
2021/03/08  17:18    <DIR>          .ipynb_checkpoints
2021/03/08  18:22             6,987 Jupyter使用规则.ipynb
               1 个文件          6,987 字节
               3 个目录 44,480,278,528 可用字节


In [63]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [64]:
%mkdir test

In [66]:
%mkdir Tests

In [67]:
%cd test

E:\jupyter_py\01-python数据分析\HZh1807\jupyter-HelloWorld\test


In [70]:
%ls

 驱动器 E 中的卷是 项目编程资料coding
 卷的序列号是 1E84-11FA

 E:\jupyter_py\01-python数据分析\HZh1807\jupyter-HelloWorld\test 的目录

2021/03/08  18:26    <DIR>          .
2021/03/08  18:26    <DIR>          ..
2021/03/08  18:26    <DIR>          .ipynb_checkpoints
2021/03/08  18:26                 0 test.txt
               1 个文件              0 字节
               3 个目录 44,480,270,336 可用字节


In [69]:
%touch t.py

UsageError: Line magic function `%touch` not found.


In [71]:
a

1024

#

![](pc_09.jpg)

![](liman.jpg)

![](liman.png)

![](https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fspider.nosdn.127.net%2F1cbce7aaf2140e43f53872b8a73f7fd9.jpeg&refer=http%3A%2F%2Fspider.nosdn.127.net&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1617791786&t=297df15f657abfbda9fe47e6899414ca)

In [74]:
import numpy as np

In [75]:

np.__version__

'1.20.1'

In [76]:
l = [1,2,3,4,5,9,8,7,6]
l

[1, 2, 3, 4, 5, 9, 8, 7, 6]

In [77]:
type(l)

list

In [78]:
nd = np.array(l)
nd

array([1, 2, 3, 4, 5, 9, 8, 7, 6])

In [79]:
type(nd)

numpy.ndarray

In [80]:
l2 = [[1,3,5,7],[2,4,6,8]]

In [81]:
l2

[[1, 3, 5, 7], [2, 4, 6, 8]]

In [82]:
nd2 = np.array(l2)
nd2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [83]:
nd2.sum()

36

In [84]:
nd.view

<function ndarray.view>

In [85]:
nd.var

<function ndarray.var>

In [86]:
nd.var()

6.666666666666667

In [87]:
x = np.arange(1,100000,1)
x

array([    1,     2,     3, ..., 99997, 99998, 99999])

In [88]:
%time x.sum()

Wall time: 998 µs


704982704

In [89]:
%timeit x.sum()

37.2 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [90]:
#py代码
def sum2(x):
    ret = 0
    for i in x:
        ret +=i
    return ret

In [91]:
%timeit sum2(x)

C:\Users\陈文亮\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in long_scalars
  """


8.59 ms ± 255 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [92]:
import pandas as pd

In [93]:
pd.__version__

'0.23.4'

In [94]:
import requests as requests

In [95]:
requests.__version__


'2.19.1'

In [96]:
np.ones(shape = (5,5),dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [97]:
np.zeros(shape = (2,3,4),dtype=np.float16)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [98]:
np.full(shape = (3,5),fill_value=3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [99]:
np.eye(N = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
np.linspace(0,100,num=101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [105]:
np.random.randint(0,100,size=(5,5))

array([[ 1, 77, 84, 15, 74],
       [96, 83, 24, 40, 38],
       [21, 68, 63, 28, 99],
       [62, 81, 88, 82, 16],
       [77, 14, 47, 32, 13]])

In [106]:
np.random.randn(4,5) #n normal正太分布      dimession维度   平均值是0 方差是1

array([[ 2.24294289, -0.77313856,  1.69131588, -1.68026657, -0.269069  ],
       [-0.29333406, -0.20844463,  0.14390657, -1.01745513, -0.89570195],
       [ 0.46029992,  1.13629969,  0.93120718, -0.11780377, -0.84344326],
       [ 0.65268991, -0.97283953,  1.50700391,  0.09292246, -1.24428749]])

In [120]:
nd = np.random.normal(loc = 175,scale = 10,size = 10000).round(2)
nd

array([165.23, 168.2 , 176.23, ..., 176.3 , 185.07, 166.25])

In [121]:
nd.mean()

175.06036300000002

In [122]:
nd.std()

9.97679595953686

In [124]:
np.random.random(100)

array([0.96651703, 0.16325822, 0.41922403, 0.7491027 , 0.84071151,
       0.11280398, 0.80623492, 0.84322378, 0.39102767, 0.27544489,
       0.12482328, 0.2125271 , 0.83216959, 0.88292731, 0.35296455,
       0.66523721, 0.78003245, 0.96051705, 0.79495891, 0.59984261,
       0.48064622, 0.35920105, 0.10330413, 0.44666198, 0.24441116,
       0.70159946, 0.83670762, 0.14211749, 0.47940343, 0.48997362,
       0.89444571, 0.27230177, 0.09609251, 0.74289407, 0.71828575,
       0.54249986, 0.2151276 , 0.056702  , 0.54806095, 0.43173864,
       0.60767148, 0.92757432, 0.8176349 , 0.24671368, 0.32053846,
       0.93500512, 0.92186491, 0.80715315, 0.28209052, 0.05278356,
       0.08004925, 0.79985957, 0.84209848, 0.85141741, 0.27824649,
       0.84706359, 0.67164107, 0.10929732, 0.23260936, 0.20021525,
       0.27663109, 0.09028103, 0.10775117, 0.89131425, 0.65574105,
       0.83837518, 0.95059661, 0.60106943, 0.08501639, 0.71574105,
       0.52495894, 0.60932577, 0.38165944, 0.96675575, 0.24204

In [129]:
from PIL import Image

ImportError: DLL load failed: 找不到指定的模块。

In [134]:
from PIL import Image

ImportError: DLL load failed: 找不到指定的模块。

In [2]:
from PIL import Image

ImportError: DLL load failed: 找不到指定的模块。

In [1]:
import Image

ModuleNotFoundError: No module named 'Image'

In [ ]:
conda install Pillow

In [ ]:
cat = Image.open('./cat.jpg')

In [ ]:
cat

In [ ]:
cat = Image.open('./cat.jpg')
cat

In [ ]:
a

In [5]:
from PIL import Image


ImportError: DLL load failed: 找不到指定的模块。

In [3]:
cat = image.open('./cat.jpg')
cat

AttributeError: module 'image' has no attribute 'open'

In [11]:
import matplotlib.pyplot as plt  # 用于画图
import matplotlib.image as mpimg  # 用于显示图片

cat = mpimg.imread('./cat.jpg')
# print(cat)
plt.imshow(cat)
plt.show()


ImportError: DLL load failed: 找不到指定的模块。

NameError: name 'plt' is not defined

In [12]:
from PIL import Image

ImportError: DLL load failed: 找不到指定的模块。

In [21]:
from PIL import Image

ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (D:\Coding\Anaconda3-5.3.1-Windows-x86_64\lib\site-packages\PIL\__init__.py)

In [17]:
image PIL.ImageMode

SyntaxError: invalid syntax (<ipython-input-17-bff1fe5241c8>, line 1)