In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import sklearn.datasets as datasets

D:\Coding\Anaconda3-5.3.1-Windows-x86_64\lib\site-packages\sklearn\linear_model\least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
D:\Coding\Anaconda3-5.3.1-Windows-x86_64\lib\site-packages\sklearn\linear_model\least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float

In [3]:
diabetes = datasets.load_diabetes()
diabetes


{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [4]:
X = diabetes['data']
y=diabetes['target']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
X_train.shape

(353, 10)

In [8]:
X_train[:5]

array([[ 0.0090156 ,  0.05068012,  0.01858372,  0.03908671,  0.01769438,
         0.01058576,  0.019187  , -0.00259226,  0.01630495, -0.01764613],
       [ 0.04897352,  0.05068012,  0.00349435,  0.07007254, -0.00844872,
         0.0134041 , -0.05444576,  0.03430886,  0.01331597,  0.03620126],
       [-0.05637009, -0.04464164, -0.07410811, -0.05042793, -0.02496016,
        -0.04703355,  0.09281975, -0.0763945 , -0.0611766 , -0.04664087],
       [ 0.04170844,  0.05068012, -0.02237314,  0.0287581 , -0.06623874,
        -0.04515466, -0.06180903, -0.00259226,  0.00286377, -0.05492509],
       [-0.01641217, -0.04464164, -0.05255187, -0.03321358, -0.0442235 ,
        -0.03638651,  0.019187  , -0.03949338, -0.06832974, -0.03007245]])

In [11]:
X_train.std(axis = 0) #数据每列的波动不大,被处理过了,归一化操作,

array([0.04735717, 0.04765916, 0.04658216, 0.04696798, 0.04749549,
       0.04810238, 0.04881012, 0.04810635, 0.04757866, 0.04825791])

In [13]:
lr = LinearRegression()

In [14]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
y_ = lr.predict(X_test) #有一点差距  y_是求解出来的值
y_.round(2)

array([123.  , 144.84, 204.55, 259.04, 106.34, 147.91, 184.59, 178.48,
       146.02,  89.78, 253.36, 181.24, 176.24, 113.28, 126.25, 165.93,
        92.77, 150.84, 153.11, 128.5 ,  73.2 ,  39.11, 111.67, 164.27,
       141.52, 180.34, 185.69, 239.48, 117.77, 121.44, 100.91, 295.9 ,
       206.87,  77.29, 145.04, 244.24, 160.42, 214.88, 187.18, 266.99,
       169.49, 147.41, 239.09, 158.95, 173.36, 143.47,  53.4 , 176.45,
       170.26, 184.74,  68.1 , 117.72, 195.8 , 125.02, 287.81, 167.7 ,
       124.14, 155.36, 231.75, 246.05, 119.85, 188.35, 158.38, 153.86,
       187.28, 241.36, 209.02, 162.56, 255.37,  98.86, 209.54, 228.33,
       125.4 , 148.93, 122.64, 144.96,  55.35, 186.99,  83.3 , 239.35,
        78.31, 184.21, 206.57, 249.21, 165.92, 125.79, 209.14, 152.34,
       143.78])

In [19]:
y_test

array([ 92., 172., 265., 336.,  90.,  81., 272., 200., 146., 113., 273.,
        70., 216.,  72., 162., 206., 115.,  97., 136.,  44., 138., 104.,
       142., 120., 200.,  77., 283., 321.,  87., 153.,  49., 270., 150.,
        92., 219., 215., 113., 163., 263., 303., 127., 185., 275.,  86.,
       111.,  40.,  65., 262., 258.,  68.,  72.,  60., 178., 191., 230.,
       178., 168.,  73., 236., 306.,  64.,  67., 129.,  95., 241., 270.,
       121., 104., 242., 104., 151., 237., 132.,  85.,  59., 168.,  63.,
       198.,  55., 261.,  77., 229., 173., 264., 245.,  71.,  52., 134.,
       190.])

In [ ]:
'''
The coefficient R^2 is defined as (1 - u/v), where u is the residual
sum of squares ((y_true - y_pred) ** 2).sum() and v is the total
sum of squares ((y_true - y_true.mean()) ** 2).sum().
The best possible score is 1.0 and it can be negative (because the
model can be arbitrarily worse). A constant model that always
predicts the expected value of y, disregarding the input features,
would get a R^2 score of 0.0.
'''


In [20]:
lr.score(X_test,y_test) #0.47448 决定系数,越大越好

0.47448931759081103

In [25]:
#((y_true - y_pred) ** 2).sum()
u = ((y_test - y_) ** 2).sum()
u

290671.1417802132

In [26]:
# ((y_true - y_true.mean()) ** 2).sum()
v = ((y_test - y_test.mean()) ** 2).sum()
v

553121.2808988764

In [27]:
1 - u/v #0.47 一样的,用的是和平均值之间的波动情况

0.47448931759081103

In [28]:
 1-np.var(y_test - y_)/np.var(y_test)

0.4795939794524433

In [29]:
np.abs(y_test - y_).mean()

47.9064142542748

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_squared_log_error

In [31]:
mean_absolute_error(y_test,y_) #

47.9064142542748